### ISSUE TITLE
Minion proposer should be able to add a short description

### ISSUE THREAD

**Issue by dekanbro** [raid-guild/moloch-minion#2]
can we allow the proposor to add a short description that will be saved to the base moloch details?

also can we add a key for isMinion

Something like:
l10
`string public constant MINION_ACTION_DETAILS = '{"isMinion": true, "title":"MINION","description": **proposors short description**}';`

**Comment by wolflo** [comment]
@dekanbro should this description be something that the deployer of the Minion sets, or something that changes for every action that's proposed?

**Comment by dekanbro** [comment]
every action. just thinking a short description that can inform the voter what it does. Could be BS but normally could be usefull.

Also thinking we should add a field for the proposers address. We could display this in the coting interface as another thing to helo inform the voter

**Comment by wolflo** [comment]
#5 has the description addition, but the frontend stuff is probably broken as a result. Let me know if it matches the way that you want to use the description, and I can update the frontend if so. I'm suspicious it may end up being off by extra spaces or quotes or something. Right now this is what it gives you: 
```javascript
await minion.proposeAction(
  action.to,
  action.value,
  action.data,
  "foobarbaz"
);
(await moloch.proposals(n)).details     //  {"isMinion": true, "title":"MINION", "description":"foobarbaz"}
```

**Comment by wolflo** [comment]
For the proposer address, do we want to add it to the `Action` struct or as a parameter to the `ActionProposed` event? Or both?

On a related note, let me know as you discover things that might be useful to add to the events. Right now the only parameters are the proposalIds.

**Comment by dekanbro** [comment]
Both
