### ISSUE TITLE
ABI decoder is converting the input to string when the function is expecting an array

### ISSUE THREAD

**Issue by dekanbro** [raid-guild/moloch-minion#58]
ABI decoder input param throws errors on Arrays

Error:
expected array value (arg="recipients", coderType="array", value="[0x68d36DcBDD7Bbf206e27134F28103abE7cf972df]")

Possible fix is to parse string back to array
NewMinion.vue L:239 setParam function
```
    setParam({ target: { id, value } }) {
      try {
        this.inputValues[id] = JSON.parse(value);
      } catch (e) {
        this.inputValues[id] = value;
      }
    },
```

**Comment by mauerv** [comment]
Can't seem to JSON.parse it because the form surrounds the value with double quotes making it invalid JSON. Maybe we need to write a custom parser for this case?

**Comment by dekanbro** [comment]
LOE: 1
