### ISSUE TITLE
add minion address to url to load page for different Minion/Molochs

### ISSUE THREAD

**Issue by dekanbro** [raid-guild/moloch-minion#65]
This will allow any daohaus MinMol (Moloch V2 with a Minion) to use the UI.

- Url would look like this: minion.raidguild.org/0x17405148473E521b62cBCf8eBd929E8A30C4D3aA
- With this address you should be able to query the minion contract and get the moloch address.
- All queries and contract calls will use these addresses
- if no address is there then default to the current raidguild contracts
- there should be a label or visual queue to inform the user which Moloch is currently being used

LOE: 4

**Comment by mauerv** [comment]
I can do this if no one is working on it already

**Comment by dekanbro** [comment]
@mauerv that would be awesome! thanks.

let me know if you have any questions. can hit me up on discord too
